### ISSUE TITLE
Either type for 3 or more values

### ISSUE THREAD

**Issue by pakoito** [eleventigers/rxeither#4]
In an exercise of copypasta, could you add the same implementation of Either for 3, 4 or more subclasses? I'd recommend to refactor Either to Either2 and make Either3, Either4 and such with basically the same code.

If you can't I can spend some time on it.

**Comment by eleventigers** [comment]
@pakoito, since either means `Each of two` in formal english grammar and this library tries to maintain simple duality of the Either type I am not sure what would be a purpose of Either3..N?

**Comment by pakoito** [comment]
Either<Left, Right > holds any two types. Either3<Left, Middle, Right> could hold up to three types, Either4<One, Two, Three, Four> for four types. Each has the same two fold() functions with one parameter per type, so implementation is fairly trivial.

If Either is not the correct term, you could think Union2, Union3, Union4 (more CS) or Sealed2, Sealed3, Sealed4 (kotlin's).

**Comment by eleventigers** [comment]
I understand the premise but then it's not Either anymore. It's either left or right - it cannot be somewhere in between. If you look at [Haskell](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Either.html) or [Scala](http://www.scala-lang.org/api/rc2/scala/Either.html) implementations you can seen that they are strictly dual. I don't think Either type would suit the idea of an ever expanding Union.

**Comment by pakoito** [comment]
THAT'S IT, I'M FORKING IT!

Nah but seriously, I'll try to tinker with it a bit over the weekend, I have some ideas.

**Comment by pakoito** [comment]
@eleventigers would you mind doing a review pass on what I've ended up with? We may need to switch to a private channel tho.

**Comment by eleventigers** [comment]
@pakoito let's do it, you can find my contacts on: https://keybase.io/eleventigers

**Comment by pakoito** [comment]
@eleventigers You have been contacted!

**Comment by eleventigers** [comment]
@pakoito :sunglasses:

**Comment by eleventigers** [comment]
@pakoito I've just started a [branch](https://github.com/eleventigers/rxeither/commit/015df79adf7460ec93bbab1f9211aa7783b3562b) which uses your [RxSealedUnions](https://github.com/pakoito/RxSealedUnions). I am happy to release it however I am not a fan of jitpack.io. Could you publish your library to MavenCentral or at least JCenter?

**Comment by pakoito** [comment]
@eleventigers Yup, give me a day.

**Comment by pakoito** [comment]
Published now at https://bintray.com/pakoito/maven/RxSealedUnions/1.0.0/view

**Comment by eleventigers** [comment]
Thanks! In with https://github.com/eleventigers/rxeither/pull/5
